Fixes/als 773 UI fixes
makeen-project/amazon-location-features-demo-ios-fork pull request #22
Opened 2023-05-18 15:03 UTC by zeeshanmakeen

ALS-773 [iOS] all buttons should be in Amazon Amber font
ALS-768 [iOS] Blips do not have shadow 
ALS-772 [iOS] Go button font and text

2023-05-19 16:17 UTC, denis-ryzhkov-makeen requested changes

2023-05-19 16:17 UTC, denis-ryzhkov-makeen commented on LocationServices/LocationServices/Scenes/Explore/Sub-Scenes/Direction/Views/Common Views/RouteTypeView.swift
> +        button.setTitle("Go", for: .normal)
let's move to constants

2023-05-19 16:17 UTC, denis-ryzhkov-makeen commented on LocationServices/LocationServices/Views/MapAnnotations/GeofenceAnnotation.swift
> +        uiImageView.layer.shadowColor = UIColor.black.cgColor
let's create an extension on UIView to add a shadow there and we can reuse it with just passing params

Also we can have a struct Style/Settings that will collect all the needed fields in order not to pass too much params into the function. This structure also could have default values for easier configuration and also static properties for reusing configurations

2023-05-22 09:31 UTC, zeeshanmakeen commented on LocationServices/LocationServices/Scenes/Explore/Sub-Scenes/Direction/Views/Common Views/RouteTypeView.swift
> +        button.setTitle("Go", for: .normal)
Done

2023-05-22 09:32 UTC, denis-ryzhkov-makeen approved these changes

2023-05-22 09:33 UTC, vadymmakeendev approved these changes

2023-05-22 09:36 UTC, merged